name: Set up Python Demo
on: workflow_dispatch
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      #Python3.12環境のセットアップ
      - name: Set up Python 3.10.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'
      
      #Pythonのバージョン確認
      name: Print Python version
      run: python --version